version: '3.8'
services:
  rabbit:
    image: rabbitmq:3.11.8-management-alpine
    ports:
      - 127.0.0.1:5672:5672 # Client port
      - 127.0.0.1:15672:15672 # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
